version: '2.1'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    restart: always
    volumes:
      - ./static/:/home/static/
      - ./conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf

