version: '2.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data:rw"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  api:
    image: api:latest
    ports:
      - "8000:8000"
    volumes:
      - "${PWD}/../score/:/home/mAdvisor/mAdvisor-api/mAdvisorScores/:rslave"
      - "./settings/:/home/mAdvisor/mAdvisor-api/config/settings/"
      - "/etc/hosts:/etc/hosts:rw"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
       test: ["CMD", "curl" ,"-f", "http://192.168.57.47:8000" ]
       interval: 10s
       timeout: 5s
       retries: 10
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    restart: always
    volumes:
      - ./static/:/home/static/
      - ./conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
  app:
    image: api:latest 
    volumes:
      - "${PWD}/apps.sh:/home/mAdvisor/mAdvisor-api/startup.sh"
    environment:
      HOST_MACHINE_IP: "192.168.57.47"
    depends_on:
      api:
        condition: service_healthy
    restart: always
