version: '2.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data:rw"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    image: api:latest
    ports:
      - "8000:8000"
    volumes:
      - "${PWD}/../score/:/home/mAdvisor/mAdvisor-api/mAdvisorScores/:rslave"
      - "./settings/:/home/mAdvisor/mAdvisor-api/config/settings/"
      - "/etc/hosts:/etc/hosts:rw"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
       test: ["CMD", "curl" ,"-f", "http://192.168.57.47:8000" ]
       interval: 10s
       timeout: 5s
       retries: 10
    restart: always
