# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 08:31
from __future__ import unicode_literals

import api.models.dataset
import api.models.errand
import api.models.robo
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(blank=True, null=True, upload_to=api.models.dataset.dataset_input_file_directory_path)),
                ('name', models.CharField(max_length=100, null=True)),
                ('userId', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Errand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('input_file', models.FileField(blank=True, null=True, upload_to=api.models.errand.errand_input_file_directory_path)),
                ('dimension', models.CharField(max_length=300, null=True)),
                ('measure', models.CharField(max_length=100, null=True)),
                ('is_archived', models.CharField(default=b'FALSE', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=300, null=True)),
                ('compare_with', models.CharField(default=b'', max_length=300)),
                ('compare_type', models.CharField(max_length=100, null=True)),
                ('column_data_raw', models.TextField(default=b'{}')),
                ('userId', models.CharField(max_length=100, null=True)),
                ('analysis_done', models.CharField(default=b'FALSE', max_length=100)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('data', models.CharField(default=b'', max_length=100)),
                ('userId', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_file', models.FileField(blank=True, null=True, upload_to=api.models.robo.robo_input_file_directory_path)),
                ('historical_file', models.FileField(blank=True, null=True, upload_to=api.models.robo.robo_input_file_directory_path)),
                ('market_file', models.FileField(blank=True, null=True, upload_to=api.models.robo.robo_input_file_directory_path)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
