# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=300)),
                ('object_id', models.CharField(max_length=300)),
                ('slug', models.SlugField(null=True)),
                ('config', models.TextField(default=b'{}')),
                ('results', models.TextField(default=b'{}')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
