# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 09:55
from __future__ import unicode_literals

import api.models.trainer
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('userId', models.CharField(max_length=100, null=True)),
                ('details', models.TextField(default=b'{}')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('input_file', models.FileField(blank=True, null=True, upload_to=api.models.trainer.local_config_file_path)),
                ('userId', models.CharField(max_length=100, null=True)),
                ('details', models.TextField(default=b'{}')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dataset')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Trainer'),
        ),
    ]
