# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
