# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170512_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='column_data_raw',
            field=models.TextField(default=b'{}'),
        ),
    ]
