# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170807_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='signals',
            name='data',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='signals',
            name='target_column',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
