# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 08:29
from __future__ import unicode_literals

import api.models.errand
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_errand_input_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.errand.errand_input_file_directory_path),
        ),
    ]
