# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-22 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trainer_column_data_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='model_data',
            field=models.TextField(default=b'{}'),
        ),
    ]
