# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170807_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='signals',
            name='config',
            field=models.TextField(default='{}'),
        ),
    ]
