# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-22 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_score_model_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='analysis_done',
            field=models.CharField(default=b'FALSE', max_length=100),
        ),
        migrations.AddField(
            model_name='trainer',
            name='analysis_done',
            field=models.CharField(default=b'FALSE', max_length=100),
        ),
    ]
