# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161215_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
