# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170522_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='app_id',
            field=models.CharField(default=b'1', max_length=10),
        ),
        migrations.AddField(
            model_name='trainer',
            name='app_id',
            field=models.CharField(default=b'1', max_length=10),
        ),
    ]
