# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_errand_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
