# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_jobdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='killed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
