# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_errand_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errand',
            old_name='dimensions',
            new_name='dimension',
        ),
    ]
