# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 10:58
from __future__ import unicode_literals

import api.models.robo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170127_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_file', models.FileField(blank=True, null=True, upload_to=api.models.robo.robo_input_file_directory_path)),
                ('portfolio_file', models.FileField(blank=True, null=True, upload_to=api.models.robo.robo_input_file_directory_path)),
                ('external_file', models.FileField(blank=True, null=True, upload_to=api.models.robo.robo_input_file_directory_path)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
