# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170606_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='column_data_raw',
            field=models.TextField(default=b'{}'),
        ),
    ]
