# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_robo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robo',
            name='external_file',
        ),
        migrations.RemoveField(
            model_name='robo',
            name='portfolio_file',
        ),
    ]
