# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 11:03
from __future__ import unicode_literals

import api.models.robo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170128_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='robo',
            name='historical_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.robo.robo_input_file_directory_path),
        ),
        migrations.AddField(
            model_name='robo',
            name='market_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.robo.robo_input_file_directory_path),
        ),
    ]
