# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170128_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
