# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_errand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='compare_with',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
