# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_errand_compare_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='compare_with',
            field=models.CharField(default=b'', max_length=300),
        ),
    ]
