# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='data',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
