# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='column_data_raw',
            field=models.TextField(default=b'{}'),
        ),
    ]
