# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_errand_column_data_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='compare_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
