# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_errand_compare_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='userId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='errand',
            name='userId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
