# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20170331_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='userId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
