# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_dataset_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='analysis_done',
            field=models.BooleanField(default=False),
        ),
    ]
