# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_errand_analysis_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='analysis_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='errand',
            name='is_archived',
            field=models.IntegerField(default=0),
        ),
    ]
