# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20170406_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='analysis_done',
            field=models.CharField(default=b'FALSE', max_length=100),
        ),
        migrations.AlterField(
            model_name='errand',
            name='is_archived',
            field=models.CharField(default=b'FALSE', max_length=100),
        ),
    ]
