# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_job_submitted_by'),
        ('api', '0042_job_error_report'),
    ]

    operations = [
    ]
