# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-05 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20180625_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdataset',
            name='crawled_data',
            field=models.TextField(default='{}'),
        ),
    ]
