# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-12 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_datasetscoredeployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetscoredeployment',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Dataset'),
        ),
        migrations.AlterField(
            model_name='datasetscoredeployment',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Score'),
        ),
    ]
