# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-13 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20190312_0717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetscoredeployment',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_trainer', 'View trainer'), ('create_trainer', 'Create trainer'), ('rename_trainer', 'Rename trainer'), ('remove_trainer', 'remove trainer'), ('downlad_pmml', 'Download PMML'))},
        ),
        migrations.AlterModelOptions(
            name='modeldeployment',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_trainer', 'View trainer'), ('create_trainer', 'Create trainer'), ('rename_trainer', 'Rename trainer'), ('remove_trainer', 'remove trainer'), ('downlad_pmml', 'Download PMML'))},
        ),
        migrations.AlterModelOptions(
            name='trainalgorithmmapping',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_trainer', 'View trainer'), ('create_trainer', 'Create trainer'), ('rename_trainer', 'Rename trainer'), ('remove_trainer', 'remove trainer'), ('downlad_pmml', 'Download PMML'))},
        ),
    ]
