# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-13 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20190313_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainalgorithmmapping',
            name='app_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
