# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-20 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0006_periodictask_priority'),
        ('api', '0067_trainalgorithmmapping_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldeployment',
            name='periodic_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask'),
        ),
    ]
