# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_modeldeployment_periodic_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customapps',
            options={'ordering': ['rank']},
        ),
        migrations.AlterField(
            model_name='dataset',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(default='Not Registered', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datasetscoredeployment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datasetscoredeployment',
            name='status',
            field=models.CharField(default='NOT STARTED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insight',
            name='status',
            field=models.CharField(default='Not Registered', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='modeldeployment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modeldeployment',
            name='status',
            field=models.CharField(default='NOT STARTED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='status',
            field=models.CharField(default='Not Registered', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainalgorithmmapping',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='status',
            field=models.CharField(default='Not Registered', max_length=100, null=True),
        ),
    ]
