# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-03 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20190411_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='shared_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='shared_slug',
            field=models.SlugField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insight',
            name='shared_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='shared_slug',
            field=models.SlugField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='messages',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='score',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='shared_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='shared_slug',
            field=models.SlugField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='mode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='shared_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='shared_slug',
            field=models.SlugField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dummy',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
