# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-01 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocr', '0004_ocrimageset_project'),
        ('ocrflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('created', 'Created'), ('submitted_for_review', 'Submitted for review'), ('reviewerL2_approved', 'ReviewerL2 Approved'), ('reviewerL2_rejected', 'ReviewerL2 Rejected'), ('reviewerL1_approved', 'ReviewerL1 Approved'), ('reviewerL1_rejected', 'ReviewerL1 Rejected'), ('superuser_approved', 'Superuser Approved'), ('superuser_rejected', 'Superuser Rejected'), ('admin_approved', 'Admin Approved'), ('admin_rejected', 'Admin Rejected')], max_length=40, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ocr_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='ocr.OCRImage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
